sudo: true
dist: xenial
language: python
services:
  - postgresql
  - redis-server
python:
  - "3.7"
cache:
  directories:
    - "$HOME/.npm"
    - .pip_download_cache
    - "$HOME/virtualenv/python3.7.1"
env:
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"
    - TRAVIS_NODE_VERSION=8.15.1
install:
  - nvm install $TRAVIS_NODE_VERSION
  - time make develop
before_script:
  - psql -c 'create database test_freight;' -U postgres
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - make lint
  - make test
